<?php
// $Id$
/**
 * @file
 * - Disables PHP block visibility permission and gives status error if a role has this permission.
 * - Disables the PHP module.
 * - Hides the PHP and paranoia modules from the modules page.
 */


/**
 * Implementation of hook_form_alter().
 */
function paranoia_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'user_admin_perm': // Disable PHP Blocks
      unset($form['permission']['use PHP for block visibility']);
      foreach (element_children($form['checkboxes']) as $rid) {
        foreach ($form['checkboxes'][$rid]['#default_value'] as $key => $value) {
          if ($value == 'use PHP for block visibility') {
          }
        }
        unset($form['checkboxes'][$rid]['#options']['use PHP for block visibility']);
      }
      break;

    case 'system_modules':   // Hide Paranoia and PHP modules from module admin form
      $hidden_modules = module_invoke_all('paranoia_hide');
      foreach($hidden_modules as $module){
        _paranoia_hide_module($form, $module);
      }
      break;
  }
}

/**
 * Remove a module from the module administration form.
 */
function _paranoia_hide_module(&$form, $module){
  unset(
    $form['validation_modules']['#value'][$module],
    $form['name'][$module],
    $form['version'][$module],
    $form['description'][$module],
    $form['throttle'][$module],
    $form['throttle']['#options'][$module],
    $form['status']['#options'][$module]
  );
}

/**
 * Implementation of hook_requirements().
 */
function paranoia_requirements($phase) {
  $requirements = array();
  if ($phase == 'runtime') {
    // Ensure that no roles have permission to use PHP for block visibility.
    module_load_include('inc', 'user', 'user.admin');
    $form = user_admin_perm($form_state);
    foreach (element_children($form['checkboxes']) as $rid) {
      if (in_array('use PHP for block visibility', $form['checkboxes'][$rid]['#default_value'])) {
        $requirements['paranoia'] = array(
          'title' => t('Paranoia'),
          'description' => t('A user role has permission to use PHP for block visibility.  Resubmit your <a href="@admin/user/permissions">user permissions</a> to close this security hole.', array('@admin/user/permissions' => url('admin/user/permissions'))),
          'severity' => REQUIREMENT_ERROR,
          );
      }
    }
    // Ensure the PHP module is not enabled.
    if (module_exists('php')) {
      $requirements['paranoia_php'] = array(
        'title' => t('Paranoia'),
        'description' => t('The PHP module is enabled.  This module should be disabled (but paranoia module prevents it from showing in the module admin form).  It may have been enabled in the database, circumventing the effectiveness of paranoia module.'),
        'severity' => REQUIREMENT_ERROR,
        );
    }
  }
  return $requirements;
}

/**
 * Implementation of hook_paranoia_hide().
 */
function paranoia_paranoia_hide() {
  return array('php', 'paranoia');
}